version: '2'
services:
    foot-app:
        image: foot
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://foot-postgresql:5432/foot
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    foot-postgresql:
        extends:
            file: postgresql.yml
            service: foot-postgresql
